services:
  db:
    container_name: postgres
    image: postgres:15.2
    environment:
      POSTGRES_USER: endava
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cars
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

  insurance-api:
    container_name: insurance-api
    build: ./backend   # <--- dacă vrei să construiești local din Dockerfile
    image: alexandrugabrielgrecu/car-insurance-api:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cars
      SPRING_DATASOURCE_USERNAME: endava
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
